/* COMP9334 Demonstration on 
   random number generation using C 

   Aim: To demonstrate the effect of seed 
   
   Compile as: cc genrand2.c -o genrand2
   Usage: ./genrand2  

   C.T. Chou, 06/04/15
*/

#include <stdio.h>
#include <stdlib.h>

int main (int argc,char *argv[])
{
  int i, seed;

  if (argc == 1)
    {  printf("Usage: './genrand2 int_seed' where int_seed is an integer\n");
       return EXIT_FAILURE; 
    }   
	          
  // Get the seed and input to srand 
  seed = atoi(argv[1]); 
  srand(seed);

  // Generate the random numbers and print them 
  printf("The random numbers generated by the seed %d are:\n",seed);
  for (i = 0; i < 10; i++)
      printf("%d\n",rand()); 
  
  return EXIT_SUCCESS; 

}
